### ISSUE TITLE
Listen Causes Infinite Loop

### ISSUE THREAD

**Issue by patrickml** [MeteorToys/allthings#49]
I have seen this on two apps now that I have made. If I turn on listen it causes an infinite loop constantly calling the same methods over and over again.

http://cl.ly/image/2B1D2m0x1t17

**Comment by mordrax** [comment]
This has been an issue for a while, my existing open issue here:
https://github.com/MeteorToys/allthings/issues/19

**Comment by msavin** [comment]
So - I thought I fixed this but its turning out to be a bit of a mystery because there is no relation between the toggle functionality of Meteor Toys and Listen, unless something is causing Tracker to go bonkers. However, I'm not using anything besides regular ReactiveDict. Just thought I'd update you guys to say I'm looking into the problem.

**Comment by msavin** [comment]
Good news - error is caught. There was a  Tracker that went  crazy, but its not clear why. I revised the way it worked, and will be pushing an update in less than 12 hours :)

**Comment by msavin** [comment]
This issue is resolved the new 2.2.0 release. To update, remove your Meteor Toys package and run `meteor add meteortoys:allthings@2.2.0`. If this issue repeats, or you have other issues, please let me know.
