### ISSUE TITLE
Unable to edit Session variable under Firefox

### ISSUE THREAD

**Issue by subk** [MeteorToys/allthings#58]
Im not able to edit Session variable using last Firefox Developer Edition
Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0

'Nullify' is working, but when clicking 'edit' button, keyboard is not responding (no error in console)

works well under Chromium

**Comment by msavin** [comment]
Strange - looks like there is a browser difference when it comes to using contenteditable. I will  look into it soon.

**Comment by msavin** [comment]
It looks like there is an issue with pre tags and contenteditable in Firefox and Safari. It seems to work fine in Chrome. I am not sure if it could be fixed because it seems browser related. I've marked it as a known issue in the Meteor Toys documentation and currently do not know how resolve it. I'll mark the issue as closed, and will update ya if I find a way to resolve it.
