### ISSUE TITLE
MeteorToys 3 meteor shell not detecting METEORTOYSSHELL

### ISSUE THREAD

**Issue by Fabs** [MeteorToys/allthings#78]
When  I run a shell command on meteor toys on browser, the output is:
"To enable Shell, you must set METEORTOYSSHELL as true on the server."

But I am running my server as:
METEORTOYSSHELL=true MONGO_URL="mongodb://localhost:27017/meteor" meteor -p 4000

So either I got it wrong (probably) or there is some issue. 

Thanks for the great product :).

**Comment by msavin** [comment]
Thanks :) I think the issue is you must set that as a global variable on the server. It sounds like you are setting it as an environmental variable. Hope that resolves it.

Best,
Max

**Comment by aadamsx** [comment]
Well did what @msavin suggest solve the issue?

**Comment by 1jerry** [comment]
What does "global variable on the server" mean?  I'm on Windows and I set METEORTOYSSHELL=true on a _system_ environment variable, started a new cmd shell and ran.  Still does not work.  I've tried off and on for almost two years and have never been able to get this to work.  What's the secret?

Why even have this extra step instead of just making it work when you are in dev mode?

**Comment by msavin** [comment]
you just need to set `METEORTOYSSHELL=true` anywhere on the server.

As for why, a lot of people make their app available over a wi-fi network, and we don't want people to go on it and run whatever code they would like on their machine
